quarkus:
  application:
    name: jeonserver
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:${db.type}:${db.url}
    username: ${db.username}
    password: ${db.password}
  hibernate-orm:
    database:
      globally-quoted-identifiers: true
  liquibase:
    migrate-at-start: true
  security:
    users:
      file:
        enabled: true
        users: users.properties
        roles: roles.properties
        realm-name: jeon
        plain-text: true
  index-dependency:
    common-api:
      group-id: io.github.ma1uta.matrix
      artifact-id: common-api
    client-api:
      group-id: io.github.ma1uta.matrix
      artifact-id: client-api

jeon:
  domain: ${jeon.domain:jeonserver.org}
